<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// use \App\Models\Model;

class ModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
    */
    public function run(): void
    {
        $models=[
            ['name'=>'Mark II', 'brand_id'=>1],
            ['name'=>'Corolla', 'brand_id'=>1],
            ['name'=>'Camry', 'brand_id'=>1],
            ['name'=>'Prius', 'brand_id'=>1],
            ['name'=>'Crown', 'brand_id'=>1],
            ['name'=>'Soarer', 'brand_id'=>1],
            ['name'=>'Avalon', 'brand_id'=>1],
            ['name'=>'Celica', 'brand_id'=>1],
            ['name'=>'Celsior', 'brand_id'=>1],
            ['name'=>'Chaser', 'brand_id'=>1],
            ['name'=>'Carina', 'brand_id'=>1],
            ['name'=>'Corona', 'brand_id'=>1],
            ['name'=>'Cresta', 'brand_id'=>1],
            ['name'=>'Supra', 'brand_id'=>1],
            ['name'=>'bZ3', 'brand_id'=>1],
            ['name'=>'bZ7', 'brand_id'=>1],
            ['name'=>'Century', 'brand_id'=>1],
            ['name'=>'Mirai', 'brand_id'=>1],
            ['name'=>'Yaris', 'brand_id'=>1],
            ['name'=>'Highlander', 'brand_id'=>1],
            ['name'=>'Harrier', 'brand_id'=>1],
            ['name'=>'RAV4', 'brand_id'=>1],
            ['name'=>'Rush', 'brand_id'=>1],
            ['name'=>'Urban Cruiser', 'brand_id'=>1],
            ['name'=>'4Runner', 'brand_id'=>1],
            ['name'=>'Fortuner', 'brand_id'=>1],
            ['name'=>'Land Cruiser', 'brand_id'=>1],
            ['name'=>'Sequoia', 'brand_id'=>1],
            ['name'=>'Alphard', 'brand_id'=>1],
            ['name'=>'Vellfire', 'brand_id'=>1],
            ['name'=>'Veloz', 'brand_id'=>1],
            ['name'=>'Calya', 'brand_id'=>1],
            ['name'=>'Hiace', 'brand_id'=>1],
            ['name'=>'Innova', 'brand_id'=>1],
            ['name'=>'Noah', 'brand_id'=>1],
            ['name'=>'Voxy', 'brand_id'=>1],
            ['name'=>'Proace', 'brand_id'=>1],
            ['name'=>'Roomy', 'brand_id'=>1],
            ['name'=>'Sienna/Granvia', 'brand_id'=>1],
            ['name'=>'Sienta', 'brand_id'=>1],
            ['name'=>'COMS', 'brand_id'=>1],
            ['name'=>'Pixis', 'brand_id'=>1],
            ['name'=>'Probox', 'brand_id'=>1],
            ['name'=>'TownAce/LiteAce', 'brand_id'=>1],
            ['name'=>'Hilux', 'brand_id'=>1],
            ['name'=>'Tacoma', 'brand_id'=>1],
            ['name'=>'Tundra', 'brand_id'=>1],
            ['name'=>'Dyna', 'brand_id'=>1],
            ['name'=>'Coaster', 'brand_id'=>1],
            ['name'=>'Sora', 'brand_id'=>1],
            ['name'=>'Toyota Publica', 'brand_id'=>1],
            ['name'=>'Toyota 2000', 'brand_id'=>1],
            ['name'=>'Allex', 'brand_id'=>1],
            ['name'=>'Allion', 'brand_id'=>1],
            ['name'=>'Aristo', 'brand_id'=>1],
            ['name'=>'Aurion', 'brand_id'=>1],
            // ['name'=>'Auris', 'brand_id'=>1],
            // ['name'=>'Avensis', 'brand_id'=>1],
            // ['name'=>'Aygo', 'brand_id'=>1],
            // ['name'=>'Bandeirante', 'brand_id'=>1],
            // ['name'=>'Belta', 'brand_id'=>1],
            // ['name'=>'Blade', 'brand_id'=>1],
            // ['name'=>'Blizzard', 'brand_id'=>1],
            // ['name'=>'Brevis', 'brand_id'=>1],
            // ['name'=>'Briska', 'brand_id'=>1],
            // ['name'=>'C+pod', 'brand_id'=>1],
            // ['name'=>'Caldina', 'brand_id'=>1],
            // ['name'=>'Cami', 'brand_id'=>1],
            // ['name'=>'Cavalier', 'brand_id'=>1],
            // ['name'=>'Classic', 'brand_id'=>1],
            // ['name'=>'Comfort', 'brand_id'=>1],
            // ['name'=>'Corsa', 'brand_id'=>1],
            // ['name'=>'Cressida', 'brand_id'=>1],
            // ['name'=>'Curren', 'brand_id'=>1],
            // ['name'=>'FA/DA', 'brand_id'=>1],
            // ['name'=>'Deliboy', 'brand_id'=>1],
            // ['name'=>'Duet', 'brand_id'=>1],
            // ['name'=>'Echo/Platz', 'brand_id'=>1],
            // ['name'=>'Esquire', 'brand_id'=>1],
            // ['name'=>'Estima/Previa', 'brand_id'=>1],
            // ['name'=>'Etios', 'brand_id'=>1],
            // ['name'=>'FJ', 'brand_id'=>1],
            // ['name'=>'Gaia', 'brand_id'=>1],
            // ['name'=>'Ipsum/Picnic/SportVan', 'brand_id'=>1],
            // ['name'=>'iQ', 'brand_id'=>1],
            // ['name'=>'Isis', 'brand_id'=>1],
            // ['name'=>'ist', 'brand_id'=>1],
            // ['name'=>'Kijang', 'brand_id'=>1],
            // ['name'=>'Lexcen', 'brand_id'=>1],
            // ['name'=>'Light Stout', 'brand_id'=>1],
            // ['name'=>'Macho', 'brand_id'=>1],
            // ['name'=>'Master', 'brand_id'=>1],
            // ['name'=>'MasterAce', 'brand_id'=>1],
            // ['name'=>'Masterline', 'brand_id'=>1],
            // ['name'=>'Matrix', 'brand_id'=>1],
            // ['name'=>'Mega Cruiser', 'brand_id'=>1],
            // ['name'=>'MiniAce', 'brand_id'=>1],
            // ['name'=>'MR-2', 'brand_id'=>1],
            // ['name'=>'Nadia', 'brand_id'=>1],
            // ['name'=>'Opa', 'brand_id'=>1],
            // ['name'=>'Origin', 'brand_id'=>1],
            // ['name'=>'Paseo/Cynos', 'brand_id'=>1],
            // ['name'=>'Passo', 'brand_id'=>1],
            // ['name'=>'Pixis', 'brand_id'=>1],
            // ['name'=>'Porte/Spade', 'brand_id'=>1],
            // ['name'=>'Premio', 'brand_id'=>1],
            // ['name'=>'Progres', 'brand_id'=>1],
            // ['name'=>'Pronard', 'brand_id'=>1],
            // ['name'=>'Publica', 'brand_id'=>1],
            // ['name'=>'QuickDelivery', 'brand_id'=>1],
            // ['name'=>'Ractis', 'brand_id'=>1],
            // ['name'=>'Raum', 'brand_id'=>1],
            // ['name'=>'Regius', 'brand_id'=>1],
            // ['name'=>'RH/SG', 'brand_id'=>1],
            // ['name'=>'Sai', 'brand_id'=>1],
            // ['name'=>'Scepter', 'brand_id'=>1],
            // ['name'=>'Sera', 'brand_id'=>1],
            // ['name'=>'Soluna', 'brand_id'=>1],
            // ['name'=>'Sparky', 'brand_id'=>1],
            // ['name'=>'Sports 800', 'brand_id'=>1],
            // ['name'=>'Sprinter', 'brand_id'=>1],
            // ['name'=>'Starlet', 'brand_id'=>1],
            // ['name'=>'Stout', 'brand_id'=>1],
            // ['name'=>'Su-Ki', 'brand_id'=>1],
            // ['name'=>'Succeed', 'brand_id'=>1],
            // ['name'=>'SunChaser', 'brand_id'=>1],
            // ['name'=>'T100', 'brand_id'=>1],
            // ['name'=>'Tank', 'brand_id'=>1],
            // ['name'=>'Tarago', 'brand_id'=>1],
            // ['name'=>'Tercel', 'brand_id'=>1],
            // ['name'=>'Tiara', 'brand_id'=>1],
            // ['name'=>'ToyoAce', 'brand_id'=>1],
            // ['name'=>'Urban', 'brand_id'=>1],
            // ['name'=>'Verossa', 'brand_id'=>1],
            // ['name'=>'Verso', 'brand_id'=>1],
            // ['name'=>'Vienta', 'brand_id'=>1],
            // ['name'=>'Vista', 'brand_id'=>1],
            // ['name'=>'Vitz', 'brand_id'=>1],
            // ['name'=>'Voltz', 'brand_id'=>1],
            // ['name'=>'Windom', 'brand_id'=>1],
            // ['name'=>'WiLL', 'brand_id'=>1],
            // ['name'=>'Wish', 'brand_id'=>1],
            // ['name'=>'Zelas', 'brand_id'=>1],




            // ['name'=>'GT-R', 'brand_id'=>2],
            // ['name'=>'370Z', 'brand_id'=>2],
            // ['name'=>'Altima', 'brand_id'=>2],
            // ['name'=>'Armada', 'brand_id'=>2],
            // ['name'=>'Cube', 'brand_id'=>2],
            // ['name'=>'Frontier', 'brand_id'=>2],
            // ['name'=>'Juke', 'brand_id'=>2],
            // ['name'=>'Kicks', 'brand_id'=>2],
            // ['name'=>'Leaf', 'brand_id'=>2],
            // ['name'=>'Maxima', 'brand_id'=>2],
            // ['name'=>'Murano', 'brand_id'=>2],
            // ['name'=>'NV Cargo/Passenger', 'brand_id'=>2],
            // ['name'=>'Pathfinder', 'brand_id'=>2],
            // ['name'=>'Patrol/Armada', 'brand_id'=>2],
            // ['name'=>'Sentra/Sylphy', 'brand_id'=>2],
            // ['name'=>'Titan/Frontier', 'brand_id'=>2],
            // ['name'=>'Versa/Sunny', 'brand_id'=>2],
            

        ];





        foreach ($models as $modely) {
            \App\Models\Modeli::create([
                'name' => $modely['name'],
                'brand_id' => $modely['brand_id']
            ]);
        };
    }
}
